@startuml
class ChangeConflictException {
    + ChangeConflictException()
    + ChangeConflictException(message:string)
    + ChangeConflictException(message:string, innerException:Exception)
}
Exception <|-- ChangeConflictException
@enduml
