@startuml
class ForeignKeyReferenceAlreadyHasValueException {
    + ForeignKeyReferenceAlreadyHasValueException()
    + ForeignKeyReferenceAlreadyHasValueException(message:string)
    + ForeignKeyReferenceAlreadyHasValueException(message:string, innerException:Exception)
}
InvalidOperationException <|-- ForeignKeyReferenceAlreadyHasValueException
@enduml
