///////////////////////////////////////////////////////////
//  Class4.cs
//  Implementation of the Class Class4
//  Generated by Enterprise Architect
//  Created on:      07-10ÔÂ-2022 15:09:42
//  Original author: ²Ü¾¸
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Package1 {
	public class Class4 {

		public Class4(){

		}

		~Class4(){

		}

	}//end Class4

}//end namespace Package1