///////////////////////////////////////////////////////////
//  Class1.cs
//  Implementation of the Class Class1
//  Generated by Enterprise Architect
//  Created on:      07-10ÔÂ-2022 15:09:42
//  Original author: ²Ü¾¸
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Package1 {
	public class Class1 {

		public Class1(){

		}

		~Class1(){

		}

	}//end Class1

}//end namespace Package1