///////////////////////////////////////////////////////////
//  Class14.cs
//  Implementation of the Class Class14
//  Generated by Enterprise Architect
//  Created on:      07-10ÔÂ-2022 15:09:42
//  Original author: ²Ü¾¸
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Package1 {
	public class Class14 {

		public Class14(){

		}

		~Class14(){

		}

	}//end Class14

}//end namespace Package1