///////////////////////////////////////////////////////////
//  Class8.cs
//  Implementation of the Class Class8
//  Generated by Enterprise Architect
//  Created on:      07-10ÔÂ-2022 15:09:42
//  Original author: ²Ü¾¸
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Package1 {
	public class Class8 {

		public Class8(){

		}

		~Class8(){

		}

	}//end Class8

}//end namespace Package1