///////////////////////////////////////////////////////////
//  Class7.cs
//  Implementation of the Class Class7
//  Generated by Enterprise Architect
//  Created on:      07-10ÔÂ-2022 15:09:42
//  Original author: ²Ü¾¸
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public class Class7 : Class8 {

		public Package1.Class6 m_Class6;

		public Class7(){

		}

		~Class7(){

		}

	}//end Class7

}//end namespace Package1