///////////////////////////////////////////////////////////
//  Class13.cs
//  Implementation of the Class Class13
//  Generated by Enterprise Architect
//  Created on:      07-10ÔÂ-2022 15:09:42
//  Original author: ²Ü¾¸
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Package1 {
	public class Class13 {

		public Class13(){

		}

		~Class13(){

		}

	}//end Class13

}//end namespace Package1