///////////////////////////////////////////////////////////
//  Class15.cs
//  Implementation of the Class Class15
//  Generated by Enterprise Architect
//  Created on:      07-10ÔÂ-2022 15:09:42
//  Original author: ²Ü¾¸
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Package1 {
	public class Class15 {

		public Class15(){

		}

		~Class15(){

		}

	}//end Class15

}//end namespace Package1