///////////////////////////////////////////////////////////
//  Class10.cs
//  Implementation of the Class Class10
//  Generated by Enterprise Architect
//  Created on:      07-10ÔÂ-2022 15:09:42
//  Original author: ²Ü¾¸
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public class Class10 {

		public Package1.Class11 m_Class11;

		public Class10(){

		}

		~Class10(){

		}

	}//end Class10

}//end namespace Package1