///////////////////////////////////////////////////////////
//  Class9.cs
//  Implementation of the Class Class9
//  Generated by Enterprise Architect
//  Created on:      07-10ÔÂ-2022 15:09:43
//  Original author: ²Ü¾¸
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public class Class9 : Interface1 {

		public Class9(){

		}

		~Class9(){

		}

	}//end Class9

}//end namespace Package1