///////////////////////////////////////////////////////////
//  Class5.cs
//  Implementation of the Class Class5
//  Generated by Enterprise Architect
//  Created on:      07-10ÔÂ-2022 15:09:42
//  Original author: ²Ü¾¸
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public class Class5 {

		public Package1.Class4 m_Class4;
		public Package1.Class3 m_Class3;

		public Class5(){

		}

		~Class5(){

		}

	}//end Class5

}//end namespace Package1