///////////////////////////////////////////////////////////
//  Class11.cs
//  Implementation of the Class Class11
//  Generated by Enterprise Architect
//  Created on:      07-10ÔÂ-2022 15:09:42
//  Original author: ²Ü¾¸
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Package1 {
	public class Class11 {
		private int T1;


		public Class11(){

		}

		~Class11(){

		}

	}//end Class11

}//end namespace Package1