///////////////////////////////////////////////////////////
//  Class12.cs
//  Implementation of the Class Class12
//  Generated by Enterprise Architect
//  Created on:      07-10ÔÂ-2022 15:09:42
//  Original author: ²Ü¾¸
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public class Class12 {

		public Package1.Class13 m_Class13;

		public Class12(){

		}

		~Class12(){

		}

	}//end Class12

}//end namespace Package1