///////////////////////////////////////////////////////////
//  Class3.cs
//  Implementation of the Class Class3
//  Generated by Enterprise Architect
//  Created on:      07-10ÔÂ-2022 15:09:42
//  Original author: ²Ü¾¸
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Package1 {
	public class Class3 {

		public Class3(){

		}

		~Class3(){

		}

	}//end Class3

}//end namespace Package1