///////////////////////////////////////////////////////////
//  Class2.cs
//  Implementation of the Class Class2
//  Generated by Enterprise Architect
//  Created on:      07-10ÔÂ-2022 15:09:42
//  Original author: ²Ü¾¸
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public class Class2 {

		public Package1.Class1 m_Class1;
		public Package1.Class3 m_Class3;

		public Class2(){

		}

		~Class2(){

		}

	}//end Class2

}//end namespace Package1