///////////////////////////////////////////////////////////
//  Class6.cs
//  Implementation of the Class Class6
//  Generated by Enterprise Architect
//  Created on:      07-10ÔÂ-2022 15:09:42
//  Original author: ²Ü¾¸
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Package1 {
	public class Class6 {

		public Class6(){

		}

		~Class6(){

		}

	}//end Class6

}//end namespace Package1