///////////////////////////////////////////////////////////
//  Interface1.cs
//  Implementation of the Interface Interface1
//  Generated by Enterprise Architect
//  Created on:      07-10ÔÂ-2022 15:09:43
//  Original author: ²Ü¾¸
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Package1 {
	public interface Interface1  {

	}//end Interface1

}//end namespace Package1