///////////////////////////////////////////////////////////
//  Interface2.cs
//  Implementation of the Interface Interface2
//  Generated by Enterprise Architect
//  Created on:      07-10ÔÂ-2022 15:09:43
//  Original author: ²Ü¾¸
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public interface Interface2  {

	}//end Interface2

}//end namespace Package1