@startuml
class ThreadAbortException <<sealed>> {
    <<internal>> ThreadAbortException()
    + ExceptionState : object? <<get>>
    - ThreadAbortException(info:SerializationInfo, context:StreamingContext)
}
SystemException <|-- ThreadAbortException
@enduml
