@startuml
class ThreadStartException <<sealed>> {
    <<internal>> ThreadStartException()
    <<internal>> ThreadStartException(reason:Exception)
    - ThreadStartException(info:SerializationInfo, context:StreamingContext)
}
SystemException <|-- ThreadStartException
@enduml
