@startuml
class ThreadExceptionEventArgs {
    - <<readonly>> m_exception : Exception
    + ThreadExceptionEventArgs(t:Exception)
    + Exception : Exception <<get>>
}
EventArgs <|-- ThreadExceptionEventArgs
@enduml
