@startuml
abstract class EnumerableExecutor {
    <<internal>> {abstract} ExecuteBoxed() : object
    <<internal>> {static} Create(expression:Expression) : EnumerableExecutor
    # EnumerableExecutor()
}
@enduml
